name: ci
on: [push, pull_request]
jobs:
  version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: 1.18
    - uses: actions/checkout@v2
    - run: go get -d -v ./...
    - run: go build
    - run: ./gnvm version
